services:
  - type: web
    name: stock-moon-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: DASH_DEBUG
        value: "False"
      - key: DASH_HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
      - key: PYTHONPATH
        value: "/opt/render/project/src"